### ISSUE TITLE
Package includes .git folder, causing errors during npm operations

### ISSUE THREAD

**Issue by jgbpercy** [supertokens/browser-tabs-lock#7] opened 2019-11-26 09:45 UTC
# Issue

browser-tabs-lock recently updated to 1.2.4, as a sub-dependency of @auth0/auth0-spa-js. This version appears to include the `.git` folder from the repo, which I believe is causing issues running npm commands on windows.

After the update, I tried to run `npm audit fix` to fix unrelated sub-dependency security warnings, and received the following error:
```
λ npm audit fix
npm ERR! code EISGIT
npm ERR! path D:\Repos\CAPP.Dashboards\dashboards-client\node_modules\browser-tabs-lock
npm ERR! git D:\Repos\CAPP.Dashboards\dashboards-client\node_modules\browser-tabs-lock: Appears to be a git repo or submodule.
npm ERR! git     D:\Repos\CAPP.Dashboards\dashboards-client\node_modules\browser-tabs-lock
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joep\AppData\Roaming\npm-cache\_logs\2019-11-26T09_24_07_358Z-debug.log
```

# Other info

The same error occurs when attempting `npm i browser-tabs-lock@"1.2.1"`. Manually removing `browser-tabs-lock` from `node_modules`, or removing the `.git` folder from inside `browser-tabs-lock` resolves the error.

Running Windows 10, npm 6.13.1.

Please let me know if any other information is needed.

**Comment by nkshah2** [comment] 2019-11-26 11:08
There seems to be a bug in npm when using ```.gitignore``` and ```.npmignore``` together, which adds .git in the packaged output even though npm states that it ignores ```.git``` file name patterns.

Working on a fix.

**Comment by nkshah2** [comment] 2019-11-26 11:31
Commit 1447220d0675f104053a61de6936e148f8b5ba1c fixes .npmignore and after verifying with ```--dry-run``` and installing version 1.2.5 from npm I can confirm that the package now works correctly. 

You should be able to re-install @auth0/auth0-spa-js and it should auto upgrade browser-tabs-lock to 1.2.5.

@jgbpercy Leaving this issue open for now, please confirm that the issue is solved, or add any other issues you face here.

**Comment by jgbpercy** [comment] 2019-11-26 11:44
@nkshah2 I can confirm this appears to have fixed the issue - thank you for the quick fix!

**Comment by nkshah2** [comment] 2019-11-26 16:22
No problem, closing this issue. Feel free to reopen it if there are more problems.

**Closed as completed** 2019-11-26 16:24 UTC
Labels: bug
