### ISSUE TITLE
Please support node 18.6

### ISSUE THREAD

**Issue by gilbahat** [supertokens/browser-tabs-lock#25] opened 2022-08-29 04:56 UTC
Hi,

1.2.15 refuses to build with node 18.8. I get the following error:

# This file contains the result of Yarn building a package (browser-tabs-lock@npm:1.2.15)
# Script name: postinstall

(node:52) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///app/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:393:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:847:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:426:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:528:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}

Node.js v18.8.0

some googling suggests this relates to a new node 18.6 feature, hope that helps.

**Comment by rishabhpoddar** [comment] 2022-08-29 06:48
We will work on this in the coming days

**Comment by porcellus** [comment] 2022-08-30 00:31
Hi, I've tried for a bit to reproduce this, but it didn't seem to happen. It's likely I'm missing something from your setup. What I've tried:
- `npm install` inside the cloned repo
- `yarn install` inside the cloned repo
- `npm i browser-tabs-lock`  inside a freshly initialized npm project
- `yarn add browser-tabs-lock`  inside a freshly initialized npm project

Are you using a custom ESM loader? (the ExperimentalWarning seems to suggest this)

**Comment by gilbahat** [comment] 2022-08-30 05:28
I was sure my codebase is nothing out of the ordinary... I will try to see what makes my configuration nonstandard and provide a test case. sorry!

**Comment by gilbahat** [comment] 2022-08-30 13:26
running yarn install using the attached package.json and yarn 3.2.0 fails. no other files are needed.
[package.json.gz](https://github.com/supertokens/browser-tabs-lock/files/9453180/package.json.gz)

**Comment by porcellus** [comment] 2022-08-30 19:10
It does indeed fail with the yarn `3.2.0` and node `18.8.0` combination, but it runs fine with `3.2.3`.
Check out this [issue](https://github.com/yarnpkg/berry/issues/4778) in yarnpkg.
I'll close this for now as it looks like it's a yarn issue. Feel free to reopen if updating didn't fix it for you.

**Closed as completed by porcellus** 2022-08-30 19:10 UTC
